version: '3.3'
services:
  app:
    image: aamv/my-books:latest
    build:
      context: ../../
      dockerfile: resources/docker/my-books-service/Dockerfile
    depends_on:
      - db
    ports:
      - '5000:8080'
    expose:
      - '5000'
    volumes:
      - /data/spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mybooksdb
      SPRING_DATASOURCE_USERNAME: aamv
      SPRING_DATASOURCE_PASSWORD: aamv
    networks:
      - backend-network

  db:
    image: mysql:latest
    # restart: always
    environment:
      MYSQL_DATABASE: 'mybooksdb'
      MYSQL_USER: 'aamv'
      MYSQL_PASSWORD: 'aamv'
      MYSQL_ROOT_PASSWORD: 'aamv'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend-network
volumes:
  my-db:
networks:
  backend-network: